### PR TITLE
Fix incorrect setup.py for PyPI

### PR DESCRIPTION
**Pull request by r3m0t**
This fixes issue #1.

---

This change is [Reviewable](https://reviewable.io/reviews/gabrielgrant/django-multiforloop/4)

### CODE REVIEW

**Comment by Oshinodono** [comment]
Hi, I don't know if someone is still carrying about this library.
But after fixing #1 I have now the message error:
InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'multiforloop.templatetags.multifor': cannot import name Library
Someone already had this error?

**Comment by Baltazar72** [comment]
I ended up with a patched version I found via google  : "django-multiforloop-patched-0.2.0"

br
Torstein

**Comment by r3m0t** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gabrielgrant/django-multiforloop/4)*

**Comment by gabrielgrant** [comment]
Hey folks, sorry for being so neglectful of this. As you can probably tell, I haven't been using this lib for a while. @r3m0t @aj-may @Mibou  If any of you are interested in helping out, more than happy to give you commit/pypi access or whatever

**Comment by r3m0t** [comment]
Yep, happy to.

**Comment by gabrielgrant** [comment]
@r3m0t i've added you to the repo on github. do you have a pypi username i can add to the project there too?

**Comment by r3m0t** [comment]
I'm `tomerc` on pypi. Could you also enable travis? https://travis-ci.org/gabrielgrant/django-multiforloop

I have a new version building here: https://travis-ci.org/r3m0t/django-multiforloop

**Comment by gabrielgrant** [comment]
Done and done :) Let me know if there's anything else I can do to get you set up

**Pull request merged**
